### ISSUE TITLE
Time set command causing steps to be 0

### ISSUE THREAD

**Issue by Anu07** [Fitpolo/FitpoloDemo_H707_Android#4]
I am issuing command to setDate and time as per device after establishing connection. But it causes steps on wearable to be zero. That is problematic. Please help.

**Comment by liuwenzheng** [comment]
What time do you set?

**Comment by liuwenzheng** [comment]
If the time you set is not the same day, the step count will reset. For example, if you take 1,000 steps today, and you set the time for tomorrow, the data will be 0. For our Fitpolo,if the device is reconnected, set the current time(calender. getInstance())

**Comment by Anu07** [comment]
If I change the timezone over my device and then update time over the wearable. Will it be causing
 the same effect?

**Comment by liuwenzheng** [comment]
Yes, it will
