### ISSUE TITLE
How do I montor for heart rate, like we do for steps?

### ISSUE THREAD

**Issue by ghost** [Fitpolo/FitpoloDemo_H707_Android#6]
Hi, I have H707 band.
I want to use band data.
How do I monitor for heart rate, like we do for steps?
Thanks.

**Comment by liuwenzheng** [comment]
Sorry, this feature is not currently supported

**Comment by liuwenzheng** [comment]
The heart rate data can only be automatically detected at time intervals, and then historical data can be read

**Comment by ghost** [comment]
Then is there any way to get information such as heart rate, step, sleep, battery?
Do you have the H707 band interlock specification?
Thanks.

**Comment by liuwenzheng** [comment]
You can run the project and read README. This document explains how to use the SDK to read and send commands
